apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  config.json: |
    {
      "data_volume": "volume/data",
      "model_volume": "volume/models",
      "input_shape": [28, 28, 1],
      "split_ratio": 0.2,
      "batch_size": 128,
      "epochs": 3,
      "lr": 0.001,
      "architecture": [
        {
          "type": "conv",
          "filters": 32,
          "size": [3, 3],
          "strides": [1, 1],
          "padding": "valid",
          "activation": "relu"
        },
        {
          "type": "max_pool",
          "size": [2, 2],
          "strides": None
        },
        {
          "type": "conv",
          "filters": 64,
          "size": [3, 3],
          "strides": [1, 1],
          "padding": "valid",
          "activation": "relu"
        },
        {
          "type": "max_pool",
          "size": [2, 2],
          "strides": None
        },
        {
          "type": "flatten"
        },
        {
          "type": "dense",
          "units": 64,
          "activation": "relu"
        },
        {
          "type": "dense",
          "units": 10,
          "activation": "softmax"
        }
      ]
    }
