apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-data
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-models
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-models
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: pv-models
  resources:
    requests:
      storage: 1Gi
